<a href="https://colab.research.google.com/github/tanmoyee04/The-Uplift-project/blob/main/Random_Forest_Classifier_using_Bagging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing the required libraries

import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
import sklearn.metrics as metrics
from sklearn.metrics import confusion_matrix

In [ ]:
# Loading the dataset

ds = load_iris()
iris = pd.DataFrame(ds.data)

In [ ]:
# Shape of dataset

print("Dataset shape: ",iris.shape) # We have 150 samples(rows) and 4 features(Columns)

Dataset shape:  (150, 4)


In [ ]:
# printing the first 5 samples

print("Dataset: ",iris.head())

Dataset:       0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2


In [ ]:
# Printing the categories

print(ds.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
# Printing the features of flowers

print(ds.feature_names) # prints the 4 features: sepal length , sepal width, petal length , petal width

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
# On the basis of features() we will decide which flower belongs to which category by training the model with the datasets that we have. 

#printing samples and target

x = iris.values[:,0:4] #Sample: feature values
y = ds.target # target: categories of flowers
print(x[0:5])
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
# Splitting the dataset into train and test

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=100)

In [ ]:
# Defining the random forest classifier

rf_clf = RandomForestClassifier(random_state=100)
rf_clf.fit(x_train,y_train) #Bagging is done to reduce variance of decision tree

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=100,
                       verbose=0, warm_start=False)

In [ ]:
# Prediction

y_pred = rf_clf.predict(x_test)
y_pred

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [ ]:
# Accuracy of the model

print("Accuracy: ",metrics.accuracy_score(y_test,y_pred))
cm=np.array(confusion_matrix(y_test,y_pred))
cm

Accuracy:  0.9555555555555556


array([[16,  0,  0],
       [ 0, 10,  1],
       [ 0,  1, 17]])